name: CI of eigen-qld

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:

  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Install dependencies
      uses: jrl-umi3218/github-actions/install-dependencies@master
      with:
        compiler: gcc
        build-type: RelWithDebInfo
        windows: |
          github:
            - path: eigenteam/eigen-git-mirror
              ref: 3.3.7
    - name: Build and test
      shell: bash
      run: |
        set -x
        mkdir -p build
        cd build
        cmake ../ -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_INSTALL_PREFIX=/c/devel/install
        cmake --build . --config RelWithDebInfo
        cmake --build . --target install --config RelWithDebInfo
        ctest -V -C RelWithDebInfo
